steps:
  # Step 1: Install dependencies from requirements.txt
  - name: 'python'
    entrypoint: 'pip'
    args: ['install', '-r', 'utils/requirements.txt']  # Removed '--user' for a more standard installation

  # Step 2: Update the Composer environment with new dependencies
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit immediately if a command exits with a non-zero status
        # Update the Composer environment with packages specified in the requirements-composer.txt
        gcloud composer environments update ${_COMPOSER_NAME} --location=${_COMPOSER_REGION} \
        --update-pypi-packages-from-file=requirements-composer.txt 2>&1 | \
        (grep -v 'No change in configuration. Must specify a change to configuration.software_configuration.pypi_dependencies' || true)
    id: 'update-composer-env'
    timeout: 3600s  # Set timeout for the update step

  # Step 3: Run the Python script to add DAGs to the Composer environment
  - name: 'python'
    entrypoint: 'python'
    args: ['utils/add_dags_to_composer.py', '--dags_directory=${_DAGS_DIRECTORY}', '--dags_bucket=${_DAGS_BUCKET}']

options:
  logging: CLOUD_LOGGING_ONLY  # Log only to Cloud Logging
