steps:
  - name: 'python:3.8-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install pytest
        pip install cloud_composer_dag_test_utils
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip list  # List installed packages for debugging
        python -m pytest -s dags/

options:
  logging: CLOUD_LOGGING_ONLY
