steps:
  # Install dependencies and run tests in one step
  - name: python:3.8-slim
    entrypoint: /bin/bash
    args:
      - -c
      - |
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install pytest
        python3.8 -m pytest -s dags/
options:
  logging: CLOUD_LOGGING_ONLY

